WIP: Setup project
ridi/cms-ui pull request #1
Opened 2018-03-14 01:16 UTC by krazijames

2018-03-16 08:38 UTC, imkitae requested changes
라이브러리다보니 버전관리가 중요할 것 같습니다. 브랜치 관리를 master, develop보다 버전명으로 구분해서 하는건 어떨까요 (현재 cms-sdk처럼.. 가령 0.x, 1.x)

2018-03-16 09:09 UTC, krazijames commented
아무래도 버전 별 브랜치가 필요하겠지요. 하지만 곧바로 버전 명을 따라 브랜치를 나누는 것 보다는 `master`를 항상 최신으로 유지하고, 메이저 버전이 변경될 때 마다 이전 버전의 브랜치를 분기시키는 방식은 어떨까요? 이를 테면 당분간은 버전이 `0.x`일테니 `master` 브랜치만 사용하다가, `1.0`이 태그되는 순간 직전 커밋을 베이스로 `0.x`브랜치를 생성하면 어떨까 싶어요. 그리고 `master`는 계속 갈길 가는거지요 ㅎㅎ

2018-03-16 09:11 UTC, krazijames commented
생각해보니 `1.0` 태그하기 전부터 분기가 필요할 수 있겠네요... 여튼 요지는 필요할 때 분기한다는 의견이었습니다.

2018-03-19 01:22 UTC, imkitae approved these changes

2018-03-19 02:08 UTC, merged